### ISSUE TITLE
Publish to nimble and one small little request

### ISSUE THREAD

**Issue by sgmihai** [z-------------/nim-bencode#3]
I'd like this lib to be published to nimble directory if you don't mind, so I don't have to have its sources in my project dir anymore. I see that the nim-bencode name is not taken.
Also, would it be possible to bring back the shorthand templates, but with "be" or something short as the identifier ? 
I have quite a few .hasKey calls on the dictionary structures and I have to prefix the key string with Bencode.. not the greatest, in this context.

**Comment by z-------------** [comment]
I've added back the shorthand as `be`.

Nimble is able to install packages directly via Git without them being published on the nimble directory, [like this](https://github.com/z-------------/swscl/blob/3d425eb98ddddc259f9ae36b7b6ca48b0e128478/swscl.nimble#L19). Have you tried that? I don't particularly want to publish to the nimble directory.

**Comment by sgmihai** [comment]
I have tried using git url in project config, works good.
And the main issue is fixed, can close this issue now.
