### ISSUE TITLE
Add package to nimble

### ISSUE THREAD

**Issue by jhgalino** [z-------------/nim-bencode#5]
Hi! Is it possible to add this package to nimble.directory for easier discoverability?

**Comment by z-------------** [comment]
Hi, I'd rather not, exactly because it would increase discoverability and thus the maintenance burden. It's pretty high up in the web search results for "nim bencode" (and in `atlas search`) anyway.

**Comment by jhgalino** [comment]
That's okay. Sounds reasonable enough.
